## numerical python

In [1]:
import numpy as np

In [2]:
arr = np.array([23,45,67,89])

In [3]:
print (arr)

[23 45 67 89]


In [4]:
arr

array([23, 45, 67, 89])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr[2]

67

In [7]:
arr[1]=32

In [8]:
arr[1]

32

In [9]:
arr

array([23, 32, 67, 89])

In [10]:
arr[3]=32

In [11]:
arr

array([23, 32, 67, 32])

In [12]:
arr1=([23,'pune',56,89])       ## homogenous

In [13]:
arr1

[23, 'pune', 56, 89]

In [15]:
arr*2

array([ 46,  64, 134,  64])

## check which one is faster . list or array

In [16]:
import time

In [17]:
time.time()

1752832673.62016

In [18]:
s = 100000

list1 = list(range (s))

arr1=np.array(list1)

### for list

In [19]:
start_time = time.time()
doubled_list = [i * 2 for i in list1]
time_list = time.time() - start_time
print("time taken by list",time_list)


time taken by list 0.011992454528808594


### for array

In [20]:
start_time = time.time()
doubled_array = [i * 2 for i in arr1]
time_array = time.time() - start_time
print("time taken by list",time_array)

time taken by list 0.02898240089416504


In [21]:
time_list / time_array

0.41378402612680054

# arange 

In [22]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
arr.ndim   ## dimension

1

## 2.d array

In [28]:
arr = np.array([[1,2,3],[4,5,6],[9,80,10],[6,8,89]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 80, 10],
       [ 6,  8, 89]])

In [29]:
arr.ndim

2

In [30]:
arr.size   ## elements

12

In [31]:
arr.shape  ## no of rows & columns

(4, 3)

In [32]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  9, 80, 10,  6,  8, 89])

In [33]:
arr.flatten().ndim

1

In [34]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 80, 10],
       [ 6,  8, 89]])

In [35]:
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 9, 80, 10,  6,  8, 89]])

## 3.d array

In [36]:
arr1 = np.array([[1,2,3],[4,5,6],[9,80,10],[6,8,89]])

In [37]:
 arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 9, 80],
       [10,  6],
       [ 8, 89]])

In [38]:
arr1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 80, 10],
       [ 6,  8, 89]])

In [39]:
arr1.ndim

2

In [40]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 9, 80]],

       [[10,  6],
        [ 8, 89]]])

In [41]:
arr1.ndim

2

## slicing

In [42]:
arr2=np.arange(3,13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
arr2[3:7]

array([6, 7, 8, 9])

In [44]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 80, 10],
       [ 6,  8, 89]])

In [45]:
arr1[1:3,0:2]

array([[ 4,  5],
       [ 9, 80]])

In [46]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 80, 10],
       [ 6,  8, 89]])

In [47]:
arr1[1:3,0:3]

array([[ 4,  5,  6],
       [ 9, 80, 10]])

In [48]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 80, 10],
       [ 6,  8, 89]])

In [49]:
np.mean(arr)

18.583333333333332

In [50]:
np.std(arr)

29.649222399396734

### linear alg

In [51]:
a = np.array([[1,4],[4,9]])
b= np.array([[3,3],[10,1]])

In [52]:
a

array([[1, 4],
       [4, 9]])

In [53]:
np.dot(a,b)

array([[ 43,   7],
       [102,  21]])

In [54]:
np.linalg.det(a)

-6.999999999999999

In [55]:
np.linalg.inv(a)

array([[-1.28571429,  0.57142857],
       [ 0.57142857, -0.14285714]])

In [56]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.65685425, 10.65685425]), eigenvectors=array([[-0.92387953, -0.38268343],
       [ 0.38268343, -0.92387953]]))

# vector

In [57]:
vec = np.array([3,6])

In [58]:
np.linalg.norm(vec)

6.708203932499369

In [59]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.

    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.

    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of th

## Problem

In [60]:
## 1. create a numpy array of shape(3,3) with value ranging from 1 to 9 

In [61]:
 a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
## 2 . given 10 numpy array [10,20,30,40,50] write code to reverse the array 

In [63]:
a = np.array([10,20,30,40,50])
rev = a[::-1]

In [64]:
rev

array([50, 40, 30, 20, 10])

In [65]:
## 3. create a 5X5 numpy array filled with zeros and set the value of middle element to 1

In [66]:

array = np.zeros((5, 5))
middle_row = 5 // 2
middle_col = 5 // 2
array[middle_row, middle_col] = 1
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [67]:
## 4 . numpy array with 20 random integer between 1 and 100 .replace all even num with -1

In [68]:
random_array = np.random.randint(1, 101, size=20)
random_array[random_array % 2 == 0] = -1

print(random_array)

[-1 55 69 -1  1 11 -1 -1 73 51 53 53 -1 23 -1 51 47 95 -1 81]


In [2]:
## 5. Given a NumPy array a = np.array([[1, 2], [3, 4], [5, 6]]) , extract the second column

In [5]:
import numpy as np 
sec = np.array([[1, 2], [3, 4], [5, 6]])
second_column = sec[:, 1]

print(second_column)


[2 4 6]


In [6]:
## 6. Create a NumPy array with values [1, 2, 3, 4] and convert it into a 2x2 matrix

In [7]:


mat = np.array([1, 2, 3, 4])
matrix = mat.reshape(2, 2)

print(matrix)


[[1 2]
 [3 4]]


In [8]:
## 7. Create two NumPy arrays of shape (2, 2) and perform element-wise addition, subtraction,multiplication, and division.

In [9]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

addition = x + y
subtraction = x - y
multiplication = x* y
division = x / y  

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
## 8.Use NumPy to create an array of 10 linearly spaced values between 0 and 1.


In [11]:
import numpy as np

linear_array = np.linspace(0, 1, 10)
print(linear_array)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [12]:
## 9.Create a NumPy array and demonstrate how to compute its mean, median, and standard deviation.


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Array:", arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Array: [1 2 3 4 5]
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [14]:
## 10.Given a 2D NumPy array, write a function to normalize each column (subtract mean and divide by std deviation).


In [16]:
import numpy as np

def normalize_columns(arr):
    mean = np.mean(arr, axis=0)
    std = np.std(arr, axis=0)
    
    std[std == 0] = 1
    
    normalized = (arr - mean) / std
    return normalized

a = np.array([[1, 2], [3, 4], [5, 6]])
normalized_a = normalize_columns(a)

print("Original array:\n", a)
print("Normalized array:\n", normalized_a)


Original array:
 [[1 2]
 [3 4]
 [5 6]]
Normalized array:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
